### ISSUE TITLE
ModuleNotFoundError: No module named 'mcdp_utils_misc'

### ISSUE THREAD

**Issue by NaoPross** [ACT4E/ACT4E-mcdp#4]
Hello,

currently we cannot solve the exercise due to this line:

https://github.com/ACT4E/ACT4E-mcdp/blame/f4ae95a16bc198b4f25b0f288a03981c6367d3df/src/act4e_mcdp/coords.py#L6

Most likely a missing file. It fails with
```
$ docker run -it --rm act4e-image-mcdp /bin/bash
root@8513b5362722:/ACT4E# act4e-mcdp-download-tests --out downloaded
Traceback (most recent call last):
  File "/usr/local/bin/act4e-mcdp-download-tests", line 5, in <module>
    from act4e_mcdp import download_main
  File "/usr/local/lib/python3.10/site-packages/act4e_mcdp/__init__.py", line 12, in <module>
    from .loading import *
  File "/usr/local/lib/python3.10/site-packages/act4e_mcdp/loading.py", line 7, in <module>
    from .coords import ComposeList, Coords, CoordsComp, CoordsIdentity
  File "/usr/local/lib/python3.10/site-packages/act4e_mcdp/coords.py", line 6, in <module>
    from mcdp_utils_misc import BoolLike, not_true
ModuleNotFoundError: No module named 'mcdp_utils_misc'
```

**Comment by NaoPross** [comment]
PSA: For the following tests of exercise 1 my hotfix will not work and crash with
```
2023-12-12 14:55:53 b3a6d55dcd5d act4e_mcdp[1] ERROR EXCEPTION: ./downloaded/lib1-parts/lib1-parts.dp-queries.FixResMaxFun.e01_empty-0000.mcdpr1.yaml - Mux - FixResMaxFun
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/act4e_mcdp/main_solve_dp_queries.py", line 146, in solve_dp_queries_main
    solution = f(model, query_data)
  File "/usr/local/lib/python3.10/site-packages/act4e_mcdp/solution_interface.py", line 221, in solve_dp_FixResMaxFun
    solution = self._call_function(fname, dp, query)
  File "/usr/local/lib/python3.10/site-packages/act4e_mcdp/solution_interface.py", line 251, in _call_function
    return f(dp, query)
  File "/usr/local/lib/python3.10/site-packages/act4e_mcdp/solution_interface.py", line 825, in solve_dp_FixResMaxFun_Mux
    cco = cco_map_value  # FIXME
NameError: name 'cco_map_value' is not defined
```

Specifically for

- `downloaded/lib1-parts/lib1-parts.dp-queries.FixFunMinRes.e01_empty-0000.mcdpr1.yaml`
- `downloaded/lib1-parts/lib1-parts.dp-queries.FixResMaxFun.e01_empty-0000.mcdpr1.yaml`

And I don't think I can comment out this part, nor have the time to look into what it is.
